version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=company_profile
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=company_profile
      - MYSQL_ROOT_PASSWORD=mysql
